// Kitty is a slightly opinionated framework based on go-kit.
// It's goal is to ease development of services deployed on Kubernetes (or any similar orchestration platform).
//
// Kitty has an opinion on:
//
// * transports: only HTTP is supported.
//
// Kitty has no opinion on:
//
// * logging: no logs are generated by default, you can plug your logger and it will get additional context,
//
// * packages: kitty only imports go-kit and the standard library,
//
// * routers: you can use any router (Gorilla Mux works out of the box, other routers can easily be plugged),
//
// * encoding: use whatever encoding you want (JSON, messagepack, protobuf, ...),
//
// * monitoring, metrics and tracing: use Istio or a sidecar process.
package kitty
